name: AWS EC2 배포 워크플로우

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1000
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 배포 시작 알림
        run: echo "배포 프로세스를 시작합니다..."

      - name: SSH로 EC2에 접속하여 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_KEY }}
          port: ${{ secrets.PI_PORT }}
          script: |
            echo "서버에 접속하여 배포를 시작합니다..."
            cd /home/joon/Server/traverse_backend

            echo "코드 최신화 중..."
            git fetch --all
            git reset --hard origin/main

            if [ -f .env.example ] && [ ! -f .env ]; then
              cp .env.example .env
            fi

            echo "Docker 컨테이너 재시작 중..."
            docker compose down
            docker compose up -d --build

            echo "불필요한 Docker 이미지 정리 중..."
            docker image prune -af

            echo "배포가 완료되었습니다."

      - name: 배포 결과 알림
        run: echo "✅배포가 성공적으로 완료되었습니다."
